### ISSUE TITLE
No pairing code, no discord server, no 'jitstreamer portal' webpage

### ISSUE THREAD

**Issue by iCRON862** [jkcoxson/JitStreamer#15]
If i want to setup jitstreamer...
- i stuck at 'Please connect to ZeroTier...' if i setup it from the website and i can't get the pairing code. Yeah i followed all the steps correctly
- there's no Discord server, only an video about an 'JitStreamer Portal' setup. The server are down, great.

Please make better instructions how to setup jitstreamer for iOS 14. I don't know what must happens at 'Please connect to ZeroTier' or what i must doing next to getting my pairing code. Thx

**Comment by JJTech0130** [comment]
> there's no Discord server

https://discord.gg/WsT2hcwRVy

> Please connect to ZeroTier

It’s kind of self-explanatory? You need to be connected to the ZeroTier VPN for JITstreamer in order for it to work…

Did you even look at https://jitstreamer.com/ ? It has detailed instructions, as well as the Discord link…

**Comment by iCRON862** [comment]
> > > there's no Discord server

> >https://discord.gg/WsT2hcwRVy

Dude, did u used the link in this repo?

> > > Please connect to ZeroTier

> It’s kind of self-explanatory? You need to be connected to the ZeroTier VPN for JITstreamer in order for it to work…

read correctly dude, i followed all the steps correctly on the webpage and tryed it multitriple times again. Nothing works.

>  Did you even look at https://jitstreamer.com/ ? It has detailed instructions, as well as the Discord link…

No, not for iOS 14. Same for the Server. There's only instructions over the shortcut that's only supports iOS 15. I NEED IT FOR iOS 14!

**Comment by jkcoxson** [comment]
My guy, chill. There’s clear instructions on iOS 14 on the site. If you need more help, go to the Discord and calm down.
