### ISSUE TITLE
Jit pair issue

### ISSUE THREAD

**Issue by antgame11** [jkcoxson/JitStreamer#23]
I cannot get past the entering of the code,

[ant@localh0st release]$ sudo ./pair
Pairing with https://jitstreamer.com, specify a different target if necessary. Pass -h for more info.
Please enter the code you got from the shortcut
33402
Error sending pair record: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("jitstreamer.com")), port: None, path: "/potential_follow_up/33402/", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1914 }]))) }, X509VerifyResult { code: 20, error: "unable to get local issuer certificate" })) }
malloc(): unaligned fastbin chunk detected
Aborted

(I compiled this myself)

**Comment by antgame11** [comment]
I fixed this by changing in the pair.rs https://jitstreamer.com to http://jitstreamer.com and it fixed the issue

**Comment by manueldeprada** [comment]
> I fixed this by changing in the pair.rs https://jitstreamer.com to http://jitstreamer.com and it fixed the issue

Worked for me! I leave here the binary for anyone too lazy to compile (and eager to trust an stranger in the internet :smile: ). Prior to this, I also experienced a SEGFAULT into glibc with the compiled version. 

I am using an updated Fedora.

[pair.zip](https://github.com/jkcoxson/JitStreamer/files/11410776/pair.zip)

**Comment by jkcoxson** [comment]
The public server has been discontinued. As such, this issue is no longer applicable.
