### ISSUE TITLE
i turn on jitstreamer says connected but doesnt work what do i do

### ISSUE THREAD

**Issue by Alexander200827** [jkcoxson/JitStreamer#25]

**Comment by ViPiMP** [comment]
Same situation over here.
I’m pretty sure the server is offline, because the Homepage is also not reachable.

**Comment by TheFIoW** [comment]
Yep, JitStreamer is down.

**Comment by SolarX666** [comment]
When will the jitstreamer reopen?

>

**Comment by BiobaTiry** [comment]
Same problem… jit not working.

**Comment by jkcoxson** [comment]
JitStreamer is now a self-hosted program. I have no plans to run another public server. I would recommend buying a cheap Raspberry pi and use Zerotier or SideStore.
