### ISSUE TITLE
macOS linking error

### ISSUE THREAD

**Issue by AlAlexAlexander** [jkcoxson/JitStreamer#27]
when running cargo build --release on my macOS Big Sur 11.7.4 it starts compiling jit_streamer v0.1.2, and shortly after gives the error: error: linking with `cc` failed: exit status: 1. 

It then gives a note containing a very long environment variable and at the end says: 
Undefined symbols for architecture x86_64:
            "_plist_dict_insert_item", referenced from:
                plist_plus::types::dictionary::_$LT$impl$u20$plist_plus..Plist$GT$::dict_insert_item::h5f8f371821980aac in libplist_plus-dffc34a83229bff2.rlib(plist_plus-dffc34a83229bff2.plist_plus.95b2badc-cgu.0.rcgu.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

It then provides one last error saying: error: could not compile `jit_streamer` due to previous error
Anyway I was wondering if anyone else had the same problem and knows how to fix it

**Comment by Starli0n** [comment]
Hi,

I have the exact same issue.
Have you manage in solving it ?
I tried to do a `cargo update` but then I have other issues...

**Comment by Legomountain14** [comment]
Having the same problem here.

**Comment by wjhat** [comment]
Still having this problem but for arm64 architecture

**Comment by AlAlexAlexander** [comment]
Still have not solved the problem, I’m really waiting for an update or response from developer.

**Comment by Legomountain14** [comment]
I have tested on multiple devices, and on both MacOS and Linux and neither have worked. I also tried downloading the source code from the latest release, and that didn't work either. 

I checked the developer's profile, and it looks like we won't get much help from him for a while.

**Comment by SternXD** [comment]
Hey guys, jkcoxson is currently away and won't be home for about another year.

**Comment by jkcoxson** [comment]
Should build again
