### ISSUE TITLE
(Code of shortcut issue)

### ISSUE THREAD

**Issue by Breelandthecat** [jkcoxson/JitStreamer#29]
Hello there! I Tried to install but the only thing that  happens is JitStreamer says "Please enter the code you got from the shortcut". I Checked my PC For a shortcut and my phone but Nothing is related to it. Can someone please help?

**Comment by nythepegasus** [comment]
JitStreamer is currently down, the only way to use it is to self host it right now. We recommend using [SideStore](https://github.com/SideStore/SideStore) in the future, as it's the software that plans to deprecate JitStreamer. Sorry for the inconvenience, you can get more info in our [Discord Server](https://discord.gg/WsT2hcwRVy).
