### ISSUE TITLE
(Windows)I cant install via USB :(

### ISSUE THREAD

**Issue by Se1d228** [jkcoxson/JitStreamer#35]
I can't install because my drivers are DEAD
![image](https://github.com/jkcoxson/JitStreamer/assets/114381573/898f7db8-a79c-4ee4-ada2-93f026d7b8e1)

Can I install it WITHOUT USB?

windows 11 23H2 beta-channel

**Comment by MADMAN-Modding** [comment]
I'd recommend trying without the beta, it may be messing something up, also try downloading motherboard drivers from the manufacturer website.

**Comment by jkcoxson** [comment]
No, you cannot pair without USB. USB is required by Apple, there is nothing that JitStreamer can do about that. Sorry!
