### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by WolfHuanHua2005** [jkcoxson/JitStreamer#39]
When I enable JIT, the prompt is as shown in the picture
![IMG_0087](https://github.com/user-attachments/assets/568d5f53-c36e-4777-9766-8aaa25f20321)

**Comment by WolfHuanHua2005** [comment]
SideJIT 4
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jkcoxson** [comment]
That's an error with SideJIT, a separate program. I'd check with @SideStore, as I'm pretty sure that's their JIT enabler. They have a Discord too.
